# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later

kind: KustomizeSchema
metadata:
  name: default-resources-starter-core
spec:
  schemas:
    elementWeb:
      limits:
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 50Mi
    matrixContentScanner:
      icap:
        limits:
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 100Mi
      clamAntiVirus:
        limits:
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 100Mi
      matrixContentScanner:
        limits:
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 100Mi
    synapse:
      haproxy:
        limits:
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
      redis:
        limits:
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      synapse:
        limits:
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 100Mi
      workers:
        limits:
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 100Mi
    wellKnownDelegation:
      limits:
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 50Mi
