# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: default-resources-starter-core
resources:
  - ./default-resources.yaml
