# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

{{- $sortedSecrets := sortAlpha (keys $.Values.secrets) -}}
{{- range $secretEntry := $sortedSecrets }}
{{- $secret := (index $.Values.secrets $secretEntry) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ess-stack.fullname" $ }}-stack-{{ $secretEntry | lower  }}
type: Opaque
data:
{{- $sortedKeys := sortAlpha (keys $secret.content) -}}
{{- range $sortedKeys }}
  {{ . }}: {{ (tpl (index $secret.content .) $) | b64enc }}
{{ end }}
---
{{ end }}
