# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


{{ range $component, $secret := $.Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ess-stack.fullname" $ }}-stack-{{ $component | lower  }}
type: Opaque
data:
{{ range $key, $value := $secret.content }}
  {{ $key }}: {{ (tpl $value $) | b64enc }}
{{ end }}
---
{{ end }}
