# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


{{ range $component, $secret := $.Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $component | lower  }}-secret
type: Opaque
data:
{{ range $key, $value := $secret.content }}
  {{ $key }}: {{ $value | b64enc }}
{{ end }}
---
{{ end }}
