# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
collections:
# ansible-galaxy is timeouting a lot, so use git as a workaround to get collections
# https://github.com/ansible/galaxy/issues/3086
- name: operator_sdk.util
  # We can't use version with operator-sdk-ansible-util because of
  # ERROR! Unexpected Exception, this is probably a bug: Non integer values in LooseVersion ('v0.4.0')
  source: https://github.com/operator-framework/operator-sdk-ansible-util.git,v0.5.0
  type: git
- name: kubernetes.core
  source: https://github.com/ansible-collections/kubernetes.core.git
  type: git
  version: "3.2.0"
- name: community.postgresql
  source: https://github.com/ansible-collections/community.postgresql.git
  type: git
  version: "3.6.1"
- name: community.general
  source: https://github.com/ansible-collections/community.general.git
  type: git
  version: "9.4.0"
- name: ansible.utils
  source: https://github.com/element-hq/ansible.utils,gaelg/fix-keep-keys-keeping-wrong-lists
  type: git
- name: ansible.posix
  source: https://github.com/ansible-collections/ansible.posix.git
  type: git
  version: "1.6.0"
- name: community.crypto
  source: https://github.com/ansible-collections/community.crypto
  type: git
  version: "2.22.1"
