# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


apiVersion: v2
name: ess-meta
description: A Helm chart to deploy ESS easily
type: application
version: 2.20.0
appVersion: "2.20.0"
dependencies:
  - name: ess-stack
    repository: https://element-hq.github.io/ess-starter-edition-core
    version: 2.20.0
  - name: ess-system
    repository: https://element-hq.github.io/ess-starter-edition-core
    version: 2.20.0
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
