# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


components_properties: "{{ query('vars', *query('ansible.builtin.varnames', 'component_info_.+')) | list | flatten }}"

images_digests: '{{ default_images_digests | combine(imported_images_digests | default({}),
  recursive=true) }}'
