# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


component_info_matrix_content_scanner:
- id: matrix_content_scanner
  application_services: false
  secret_name_is_optional: true
  synapse_additional_ingress_paths: "{{ _matrix_content_scanner_basic_paths + (_matrix_content_scanner_additional_paths | default([])) }}"

_matrix_content_scanner_basic_paths:
- path: /_matrix/media_proxy
  matchHostname: '{{ components.synapse.k8s.ingress.fqdn }}'
  availability: internally_and_externally  # /_matrix/media_proxy should also be available when hitting Synapse's HAProxy Service directly
  service:
    name: '{{ ansible_operator_meta.name }}-matrix-content-scanner'
    port:
      name: web
