# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: Maintain Manifest
  block:
  - name: Apply Manifest
    no_log: "{{ lookup('env', 'DEBUG_MANIFESTS') | int != 1 }}"
    kubernetes.core.k8s:
      resource_definition: "{{ _manifest }}"
  rescue:
  - name: Destroy Manifest
    no_log: "{{ lookup('env', 'DEBUG_MANIFESTS') | int != 1 }}"
    kubernetes.core.k8s:
      state: absent
      resource_definition: "{{ _manifest }}"

  - name: Apply Manifest from scratch
    no_log: "{{ lookup('env', 'DEBUG_MANIFESTS') | int != 1 }}"
    kubernetes.core.k8s:
      resource_definition: "{{ _manifest }}"
