# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
# Because of https://github.com/kubernetes/kubernetes/issues/117356
# We might have to delete/recreate resources
- name: Maintain Manifest
  block:
  - name: Apply Manifest
    kubernetes.core.k8s:
      resource_definition: "{{ _element_manifest }}"
    register: _apply
  rescue:
  - name: Destroy Manifest when they cant be redeployed
    when: ('missing metadata in converted object' in _apply.msg)
    block:
    - name: Destroy Manifest
      kubernetes.core.k8s:
        state: absent
        resource_definition: "{{ _element_manifest }}"

    - name: Apply Manifest from scratch
      kubernetes.core.k8s:
        resource_definition: "{{ _element_manifest }}"

  - name: Throw error if it is not Manifest spec update related
    when: ('missing metadata in converted object' not in _apply.msg)
    ansible.builtin.fail:
      msg: "{{ _apply.msg }}"
