# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: Maintain StatefulSet
  block:
  - name: Apply StatefulSet
    kubernetes.core.k8s:
      resource_definition: "{{ _statefulset_manifest }}"
    register: _sts
  rescue:
  - name: Destroy StatefulSet when they cant be redeployed
    when: "'updates to statefulset spec for fields other than' in _sts.msg"
    block:
    - name: Destroy StatefulSet
      kubernetes.core.k8s:
        state: absent
        resource_definition: "{{ _statefulset_manifest }}"

    - name: Apply StatefulSet from scratch
      kubernetes.core.k8s:
        resource_definition: "{{ _statefulset_manifest }}"

  - name: Throw error if it is not StatefulSet spec update related
    when: "'updates to statefulset spec for fields other than' not in _sts.msg"
    ansible.builtin.fail:
      msg: "{{ _sts.msg }}"
