# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


resources:
  # All RBAC will be applied under this service account in
  # the deployment namespace. You may comment out this resource
  # if your manager will use a service account that exists at
  # runtime. Be sure to update RoleBinding and ClusterRoleBinding
  # subjects if changing service account names.
  - leader_election_role.yaml
  # Comment the following 4 lines if you want to disable
  # the auth proxy (https://github.com/brancz/kube-rbac-proxy)
  # which protects your /metrics endpoint.
  - auth_proxy_role.yaml
  - auth_proxy_client_clusterrole.yaml
