# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


kind: KustomizeSchema
metadata:
  name: pods-security-context
spec:
  schema:
    description: "A subset of PodSecurityContext. PodSecurityContext holds pod-level security attributes and common container settings"
    type: object
    properties:
      fsGroup:
        type: integer
        format: int64
        description: |
          A special supplemental group that applies to all containers in a pod. Some volume types allow the Kubelet to
          change the ownership of that volume to be owned by the pod:

          1. The owning GID will be the FSGroup
          2. The setgid bit is set (new files created in the volume will be owned by FSGroup)
          3. The permission bits are OR'd with rw-rw----

          If unset, the Kubelet will not modify the ownership and permissions of any volume.
      fsGroupChangePolicy:
        type: string
        description: "fsGroupChangePolicy defines behavior of changing ownership and permission of the volume before being exposed inside Pod. This field will only apply to volume types which support fsGroup based ownership(and permissions). It will have no effect on ephemeral volume types such as: secret, configmaps and emptydir. Valid values are \"OnRootMismatch\" and \"Always\". If not specified, \"Always\" is used."
      runAsGroup:
        description: The GID to run the entrypoint of the container process. Uses runtime default if unset.
        format: int64
        type: integer
      runAsNonRoot:
        description: Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed.
        type: boolean
      runAsUser:
        description: The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified.
        format: int64
        type: integer
      supplementalGroups:
        description: A list of groups applied to the first process run in each container, in addition to the container's primary GID. If unspecified, no groups will be added to any container.
        type: array
        items:
          format: int64
          type: integer
      seccompProfile:
        description: To set the Seccomp profile for a Container, include the seccompProfile field in the securityContext section of your Pod or Container manifest. The seccompProfile field is a SeccompProfile object consisting of type and localhostProfile. Valid options for type include RuntimeDefault, Unconfined, and Localhost. localhostProfile must only be set set if type Localhost. It indicates the path of the pre-configured profile on the node, relative to the kubelet's configured Seccomp profile location (configured with the --root-dir flag).
        type: object
        properties:
          type:
            type: string
            enum:
              - RuntimeDefault
              - Unconfined
              - Localhost
          localhostProfile:
            type: string
