# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


kind: KustomizeSchema
metadata:
  name: workloads
spec:
  schema:
    description: Custom properties on workloads
    type: object
    properties:
      annotations:
        description: Defines the annotations to add to the workloads
        type: object
        additionalProperties:
          type: string
      extraEnv:
        description: Defines additional environment variables to be injected onto this workload
        type: array
        items:
          description: A single env var to be injected onto this workload
          type: object
          required:
            - name
            - value
          properties:
            name:
              description: Name of the environment variable
              type: string
            value:
              description: Value of the environment variable
              type: string
