# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


kind: KustomizeSchema
metadata:
  name: workloads
spec:
  schema:
    description: Custom properties on workloads
    type: object
    properties:
      annotations:
        description: Defines the annotations to add to the workloads
        type: object
        additionalProperties:
          type: string
      extraEnv:
        description: Defines additional environment variables to be injected onto this workload
        type: array
        items:
          description: A single env var to be injected onto this workload
          type: object
          required:
            - name
            - value
          properties:
            name:
              description: Name of the environment variable
              type: string
            value:
              description: Value of the environment variable
              type: string
      nodeSelector:
        description: 'NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node''s labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/'
        type: object
        additionalProperties:
          type: string
      tolerations:
        description: "Workload tolerations"
        type: array
        items:
          description: The pod this Toleration is attached to tolerates any taint that matches the triple <key,value,effect> using the matching operator <operator>.
          properties:
            effect:
              description: Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.
              type: string
            key:
              description: Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys.
              type: string
            operator:
              description: Operator represents a key's relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category.
              type: string
            tolerationSeconds:
              description: TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system.
              type: number
            value:
              description: Value is the taint value the toleration matches to. If the operator is Exists, the value should be empty, otherwise just a regular string.
              type: string
          type: object
