# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


kind: KustomizeSchema
metadata:
  name: k8s-services
spec:
  schema:
    type: object
    default: {}
    description: Settings dedicated to services
    properties:
      type:
        type: string
        description: Default service type
        enum:
          - ClusterIP
          - NodePort
          - LoadBalancer
