# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


kind: KustomizeSchema
metadata:
  name: matrixContentScanner
spec:
  schema:
    type: object
    required:
      - scanning
      - caching
    properties:
      scanning:
        type: object
        description: Scanning configuration
        properties:
          allowedMimetypes:
            description: List of allowed MIME types. If a file has a MIME type that's not in this list, its scan is considered failed. Allow every MIME types by default.
            type: array
            items:
              type: string
              description: A MIME type.
      caching:
        type: object
        description: Configures caching of scan results.
        default: {}
        anyOf:
          - required: [maxFileSize]
          - {}
        properties:
          cacheSize:
            description: Maximum number of results that can be stored in the cache. If more files are scanned before existing items reach their TTL, the least-recently accessed will be evicted.
            type: number
            default: 1024
          ttl:
            description: The maximum amount of time an entry will stay in the cache before being evicted.
            pattern: "[0-9]+[dwmy]+"
            type: string
            default: 1d
          maxFileSize:
            description: The maximum cachable file size. If a file is bigger than this size, a copy of it will be not be cached even if the scan succeeds. If the file is requested again, it is downloaded again from the homeserver, but is not written to disk or scanned.
            type: string
            pattern: "[0-9]+[KMGT]B"
