# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


kind: KustomizeSchema
metadata:
  name: postgres-libpq
spec:
  schema:
    description: Configuration of the PostgreSQL database
    type: object
    required:
      - host
      - user
      - database
    properties:
      host:
        description: PostgreSQL database host
        type: string
      port:
        description: PostgreSQL port
        type: integer
        default: 5432
        minimum: 0
        maximum: 65535
      user:
        description: PostgreSQL username
        type: string
      database:
        description: PostgreSQL database name
        type: string
      sslMode:
        description: TLS settings to use for the PostgreSQL connection
        type: string
        default: require
        enum:
          - disable
          - allow
          - prefer
          - require
          - verify-ca
          - verify-full
      passwordSecretKey:
        type: string
        description: The PostgreSQL password
        default: postgresPassword
