# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


kind: KustomizeSchema
metadata:
  name: synapse
spec:
  schema:
    type: object
    default: {}
    properties:
      externalAppservices:
        type: object
        default: {}
        description: External application services to configure
        properties:
          files:
            type: object
            default: {}
            description: Map of appservice registration files to inject
            additionalProperties:
              type: string
              description: Content of an appservice registration file
          configMaps:
            type: array
            default: []
            description: Array of ConfigMaps containing a registration.yaml to mount in synapse
            items:
              type: string
              description: A configmap name
      media:
        type: object
        default:
          volume:
            size: 50Gi
        properties:
          volume:
            type: object
            description: The volume holding media
            default:
              size: 50Gi
            oneOf:
              - required:
                  - size
                not:
                  required:
                    - name
              - required:
                  - name
                  - size
            properties:
              name:
                type: string
                description: The volume name to use to store the media
              size:
                anyOf:
                  - type: integer
                  - type: string
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[MGTPE])?$
                x-kubernetes-int-or-string: true
                description: The volume size to use to store the media
      macaroonSecretKey:
        type: string
        default: macaroon
        description: The key of the k8s secret containing Synapse Macaroon
      registrationSharedSecretSecretKey:
        type: string
        default: registrationSharedSecret
        description: The key of the k8s secret containing Synapse registration shared secret
      signingKeySecretKey:
        type: string
        default: signingKey
        description: The key of the k8s secret containing Synapse signing key
      postgresql:
        description: This field will be replaced by kustomize
      log:
        description: Synapse Logging settings
        type: object
        default: {}
        properties:
          rootLevel:
            type: string
            description: The maximum level of Synapse log output before any overrides
            default: Info
            enum:
              - Critical
              - Error
              - Warning
              - Info
              - Debug
          levelOverrides:
            description: Logging level overrides for specific Synapse loggers
            type: object
            additionalProperties:
              description: The maximum level of Synapse log output for this specific logger
              type: string
              enum:
                - Critical
                - Error
                - Warning
                - Info
                - Debug
      workers:
        description: Workers configuration
        type: array
        default: []
        items:
          type: object
          required:
            - type
          properties:
            type:
              description: Type of worker being configured
              type: string
              enum:
                - appservice
                - background
                - client-reader
                - encryption
                - event-creator
                - event-persister
                - federation-inbound
                - federation-reader
                - federation-sender
                - initial-synchrotron
                - media-repository
                - presence-writer
                - pusher
                - receipts-account
                - sso-login
                - synchrotron
                - typing-persister
                - user-dir
            instances:
              description: Number of instances of this worker type
              type: integer
              default: 1
            additional:
              default: ''
              description: Arbitrary extra config to inject into the Synapse worker configuration as a YAML string
              type: string
            resources:
              description: This field will be generated by kustomize
      additional:
        type: string
        description: Additional config to inject
