# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


kind: KustomizeSchema
metadata:
  name: wellKnownDelegation
spec:
  schema:
    type: object
    default: {}
    properties:
      additionalClientConfig:
        type: string
        description: WellKnownDelegation additional client configuration.
      additionalServerConfig:
        type: string
        description: WellKnownDelegation additional server configuration.
