apiVersion: v1
kind: Service
metadata:
{{- if $.Values.crds.conversionWebhook.annotations }}
  annotations:
    {{- toYaml $.Values.crds.conversionWebhook.annotations | nindent 4 }}
{{- end }}
  name: '{{ include "__CHART_FUNCTIONS_NAMESPACE__.conversionWebhookFullname" . }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 7443
  selector:
    app.kubernetes.io/instance: '{{ include "__CHART_FUNCTIONS_NAMESPACE__.conversionWebhookFullname" . }}'
