{{- if $.Values.deployCrds }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "__CHART_FUNCTIONS_NAMESPACE__.conversionWebhookFullname" . }}'
  namespace: '{{ .Release.Namespace }}'
{{ end }}
