# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: controller-manager
  name: controller-manager-metrics
  namespace: system
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/instance: controller-manager
