# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---

# We convert all the items to dicts, merge them (removing duplicates), and extract them out to items again
api_env: "{{ {} | combine(([api_env_underrides, api_env_user]
                    + (query('vars', *(query('ansible.builtin.varnames', '.+_env_overrides$')
                                      )
                             ) | list
                      )
                    )
                  | map('items2dict', key_name='name'))
                | dict2items(key_name='name') }}"
