# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common
  - old/v1alpha1_elementdeployment.yaml
# Inject old versions
replacements:
  - source:
      kind: KustomizeSchema
      name: elementdeployment-starter-core-v1alpha1
      fieldPath: spec
    targets:
      - select:
          kind: CustomResourceDefinition
          name: elementdeployments.matrix.element.io
        fieldPaths:
          - spec.versions.1
patches:
  - path: element_web.yaml
    target:
      kind: CustomResourceDefinition
      name: elementdeployments.matrix.element.io
  - path: matrix_content_scanner.yaml
    target:
      kind: CustomResourceDefinition
      name: elementdeployments.matrix.element.io
  - path: sliding_sync.yaml
    target:
      kind: CustomResourceDefinition
      name: elementdeployments.matrix.element.io
  - path: synapse.yaml
    target:
      kind: CustomResourceDefinition
      name: elementdeployments.matrix.element.io
  - path: well_known_delegation.yaml
    target:
      kind: CustomResourceDefinition
      name: elementdeployments.matrix.element.io
