# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later



- op: add
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/slidingSync'
  value:
    type: object
    description: Sliding Sync is a backend component required by the Element X client beta. It provides a mechanism for the fast synchronisation of Matrix rooms. It is not recommended for production use and is only provide to enable the usage of the Element X client. The current version does not support SSO (OIDC/SAML/CAS). If you wish to try out the Element X client, then you need to be using password-based auth to allow Sliding Sync to work. SSO support (OIDC/SAML/CAS) will be added with a later version of the Sliding Sync tooling.
    properties:
      secretName:
        default: sliding-sync
        type: string
        description: The secret data associated to SlidingSync config
        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
        maxLength: 253
      config:
        description: This field will be replaced by kustomize
      k8s:
        type: object
        default: {}
        properties:
          common:
            description: This field will be replaced by kustomize
          ingress:
            description: This field will be replaced by kustomize
          api:
            type: object
            default: {}
            properties:
              workloads:
                description: This field will be replaced by kustomize
              monitoring:
                description: This field will be replaced by kustomize
