# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


- op: add
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/synapse'
  value:
    type: object
    description: This is a matrix homeserver.
    required:
      - config
    properties:
      secretName:
        default: synapse
        type: string
        description: The secret data associated to synapse config Key matching `config.macaroonSecretKey`, `config.registrationSharedSecretSecretKey`, `config.signingKeySecretKey`, `config.adminPasswordSecretKey`, `config.telemetry.password` and `config.postgres.passwordSecretKey` must be present. If ingress is tls mode is using certificate, key matching `k8s.ingress.certificate.certFileSecretKey` and `k8s.ingress.certificate.privateKeySecretKey` must be present If stun is enabled, key matching `config.stun.sharedSecretSecretKey` must be present. To override synapse default trust store for federation, every keys of `config.federation.certificateAutoritiesSecretKeys` should be present.
        pattern: ^[a-z0-9]([\-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([\-a-z0-9]*[a-z0-9])?)*$
        maxLength: 253
      config:
        description: This field will be replaced by kustomize
      k8s:
        type: object
        description: You can override Kubernetes configuration for each component of Synapse
        default: {}
        properties:
          common:
            description: This field will be replaced by kustomize
          ingress:
            description: This field will be replaced by kustomize
          synapse:
            type: object
            description: k8s properties of the synapse workloads inside synapse component
            default: {}
            properties:
              common:
                description: This field will be replaced by kustomize
              workloads:
                description: This field will be replaced by kustomize
              storage:
                description: This field will be replaced by kustomize
              monitoring:
                description: This field will be replaced by kustomize
          haproxy:
            type: object
            description: k8s properties of the haproxy workloads inside synapse component
            default: {}
            properties:
              workloads:
                description: This field will be replaced by kustomize
          redis:
            type: object
            description: k8s properties of the redis workloads inside synapse component
            default: {}
            properties:
              workloads:
                description: This field will be replaced by kustomize
