# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: elementdeployments.matrix.element.io
spec:
  group: matrix.element.io
  names:
    kind: ElementDeployment
    listKind: ElementDeploymentList
    plural: elementdeployments
    singular: elementdeployment
  scope: Namespaced
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundleReplacedByHelmBuild:
        service:
          namespace: system
          name: element-conversion-webhook
          path: /convert
      conversionReviewVersions:
        - v1
        - v1beta1
  versions:
    - name: v1alpha2
      schema:
        openAPIV3Schema:
          description: ElementDeployment is the Schema for the elementdeployments API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of ElementDeployment
              type: object
              required:
                - global
              properties:
                global:
                  type: object
                  required:
                    - config
                  properties:
                    k8s:
                      type: object
                      default: {}
                      properties:
                        common:
                          description: This field will be replaced by kustomize
                        ingresses:
                          description: This field will be replaced by kustomize
                        workloads:
                          description: This field will be replaced by kustomize
                        storage:
                          description: Global storage configuration
                          type: object
                          properties:
                            storageClassName:
                              type: string
                              description: The storage class name to use
                        monitoring:
                          description: This field will be replaced by kustomize
                    config:
                      description: This field will be replaced by kustomize
                    secretName:
                      type: string
                      description: The secret holding the global data
                      default: global
                      pattern: ^[a-z0-9]([\-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([\-a-z0-9]*[a-z0-9])?)*$
                      maxLength: 253
                components:
                  type: object
                  default: {}
                  properties: {}
            status:
              description: Status defines the observed state of ElementDeployment
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: ElementDeployment is the Schema for the elementdeployments API
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            status:
              description: Status defines the observed state of ElementDeployment
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              description: This field will be replaced by Kustomize
      served: true
      storage: false
      deprecated: true
      subresources:
        status: {}
