# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
{{- $postgresPassword := include "ess.secrets.passwords.manage-with-default" (dict "secret" (printf "%s-stack-synapse" (include "ess-stack.fullname" $)) "key" "postgresPassword" "defaultPasswordValue" (include "ess.secrets.password.shared-password" (dict "sharedPasswordId" "synapse-pg-password" "context" $)) "context" $) -}}
{{- $adminPassword := include "ess.secrets.passwords.manage" (dict "secret" (printf "%s-postgres-db" .Release.Name) "key" "adminPassword" "context" $) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-db
type: Opaque
data:
  adminPassword: {{ $adminPassword }}
  synapsePassword: {{ $postgresPassword | b64enc | quote }}
