# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
image_repository: matrixdotorg/synapse
image_pull_secrets: []

image_synapse_has_digest: "{{ (image.digest | default('')) | length > 0 }}"
image_synapse_pull_policy: "{{ image_synapse_has_digest | ternary('IfNotPresent', 'Always') }}"
image_haproxy_has_digest: "{{ (image.haproxy_digest | default('')) | length > 0 }}"
image_haproxy_pull_policy: "{{ image_haproxy_has_digest | ternary('IfNotPresent', 'Always') }}"
image_redis_has_digest: "{{ (image.redis_digest | default('')) | length > 0 }}"
image_redis_pull_policy: "{{ image_redis_has_digest | ternary('IfNotPresent', 'Always') }}"

_pass_uid_lookup:
  Always: true
  Never: false

_pass_uid_default: 'Always'
_pass_uid: "{{ is_openshift and _pass_uid_lookup[image.pass_user_id_to_synapse | default(_pass_uid_default)] }}"

env_underrides: []
env_user: "{{ workloads.synapse.extra_env | default([]) }}"
env_overrides: "{{ env_default + (_pass_uid | ternary(env_openshift, [])) }}"
env_default:
- name: SYNAPSE_WORKER
  value: "{{ process_app }}"
- name: SSL_CERT_DIR
  value: "/etc/ssl/certs"
env_openshift:
- name: UID
  value: "{{ openshift_uid_base | default(100000) }}"
- name: GID
  value: "0"

# We convert all the items to dicts, merge them (removing duplicates), and extract them out to items again
env: "{{ {} | combine([env_underrides, env_user, env_overrides] | map('items2dict', key_name='name'))
            | dict2items(key_name='name') }}"

redis_image_repository: "redis"
redis_image_tag: "6.2"
redis_loglevel: "warning"

haproxy_image_repository: "haproxy"
haproxy_image_tag: "2.4"
haproxy_replicas: 2

secrets_hash: "{{ _fetched_synapse_secrets | hash('sha1') }}"

_parsed_synapse_secrets:
  database_password: "{{ _fetched_synapse_secrets.resources[0].data['postgresPassword'] | b64decode }}"
  macaroon: "{{ _fetched_synapse_secrets.resources[0].data['macaroon'] | b64decode }}"
  registration_shared: "{{ _fetched_synapse_secrets.resources[0].data['registrationSharedSecret'] | b64decode }}"
homeserver_yaml: "{{ lookup('template', 'homeserver.yaml.j2') }}"
log_config_yaml: "{{ lookup('template', 'log_config.yaml.j2') }}"
redis_config: "{{ lookup('template', 'redis.conf.j2') }}"
