# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


apiVersion: matrix.element.io/v1alpha1
kind: MatrixContentScanner
metadata:
  labels:
    app.kubernetes.io/name: matrixcontentscanner
    app.kubernetes.io/instance: matrixcontentscanner-sample
    app.kubernetes.io/part-of: element-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: element-operator
  name: matrixcontentscanner-sample
spec:
  image:
    matrixContentScanner:
      tag: v1.0.3
    clamAntiVirus:
      tag: "1.1.0"
    icap:
      tag: core-0.5.10-mod-0.5.5
  config:
    externalSecret:
      name: matrixcontentscanner-secrets
    matrixServer:
      baseUrl: http://synapse.dev.local
      domainName: dev.local
    scanning:
      allowedMimetypes: ["image/jpeg"]
    clamAntiVirus:
      volumeClaim: "clamav-pvc"
    caching:
      exitCodesToIgnore: [1, 2]
      maxSize: 2048
      ttl: "1d"
      maxFileSize: "100MB"
      persistentVolumeClaimTemplate:
        size: 1Gi
        storageClassName: standard
        selector:
          matchLabels:
            app.kubernetes.io/instance: matrixcontentscanner
    download:
      additional_headers:
        user-agent: "matrix-content-scanner"
