# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "Manage manifests"
  ansible.builtin.include_role:
    name: "generic_apply"
  vars:
    _manifest_files: "{{ query('fileglob', 'templates/manifests/*.yaml.j2') }}"
