# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


namePrefix:
clusterDeployment: true
deployCrds: true
deployCrdRoles: true
deployManager: true

crds:
  annotations: {}
  conversionWebhook:
    extraPodSpec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
    extraContainerSpec:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
          - ALL
    tlsSecretName: ""
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 50Mi
    imagePullPolicy: Always
    image:
      repository: docker.io/vectorim/ess-core-updater-conversion-webhook
      tag: 2.15.1

updater:
  extraPodSpec:
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      fsGroup: 65532
  manager:
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 10m
        memory: 256Mi
    imagePullPolicy: Always
    extraEnvs:
    - name: DEBUG_MANIFESTS
      value: "0"
    - name: ANSIBLE_VERBOSITY
      value: "1"
    extraContainerSpec:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
          - ALL
    image:
      repository: docker.io/vectorim/ess-core-updater
      tag: 2.15.1

  rbacProxy:
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 10m
        memory: 256Mi
    extraContainerSpec:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
          - ALL
    imagePullPolicy: Always
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.13.1
  conversion-webhook:
    image:
      repository: ""
