{{- if $.Values.clusterDeployment }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: '{{ .Values.clusterDeployment | ternary "ClusterRole" "Role" }}Binding'
metadata:
  name: '{{ .Values.prefix }}-proxy'
  {{- if not $.Values.clusterDeployment }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: '{{ .Values.clusterDeployment | ternary "ClusterRole" "Role" }}'
  name: '{{ .Values.prefix }}-proxy'
subjects:
  - kind: ServiceAccount
    name: '{{ .Values.prefix }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'
{{ end }}
