{{- if $.Values.deployCrdRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: '{{ .Values.clusterDeployment | ternary "ClusterRole" "Role" }}'
metadata:
  name: elementdeployment-viewer
  {{- if not $.Values.clusterDeployment }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  {{- if $.Values.clusterDeployment }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- end }}
rules:
  - apiGroups:
      - matrix.element.io
    resources:
      - elementdeployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - matrix.element.io
    resources:
      - elementdeployments/status
    verbs:
      - get
{{ end }}
