{{- if $.Values.deployManager }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ include "elementUpdater.prefix" . }}-leader-election'
  namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "elementUpdater.prefix" . }}-leader-election'
subjects:
  - kind: ServiceAccount
    name: '{{ include "elementUpdater.prefix" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'
{{ end }}
