{{- if $.Values.deployManager }}
{{- if $.Values.clusterDeployment }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Values.prefix }}-controller-manager'
  name: '{{ .Values.prefix }}-controller-manager-metrics'
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/instance: '{{ .Values.prefix }}-controller-manager'
{{ end }}
{{ end }}
