# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

{{ if or (eq (index .Values "element-operator").deployCrds true) (eq (index .Values "element-updater").deployCrds true) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ess-system.fullname" $ }}-{{ (index .Values "element-updater").namePrefix }}-conversion-webhook-tls
  namespace: {{ .Release.Namespace }}
spec:
  commonName: {{ include "ess-system.fullname" $ }}-{{ (index .Values "element-updater").namePrefix }}-conversion-webhook.{{ .Release.Namespace }}.svc
  dnsNames:
  - {{ include "ess-system.fullname" $ }}-{{ (index .Values "element-updater").namePrefix }}-conversion-webhook.{{ .Release.Namespace }}.svc
  secretName: {{ include "ess-system.fullname" $ }}-{{ (index .Values "element-updater").namePrefix }}-selfsigned-certs
  # 1 year
  duration: 8766h0m0s
  # 6 months
  renewBefore: 4380h0m0s
  privateKey:
    algorithm: RSA
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
  issuerRef:
    name: {{ include "ess-system.fullname" $ }}-webhook
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ess-system.fullname" $ }}-{{ (index .Values "element-operator").namePrefix }}-conversion-webhook-tls
  namespace: {{ .Release.Namespace }}
spec:
  commonName: {{ include "ess-system.fullname" $ }}-{{ (index .Values "element-operator").namePrefix }}-conversion-webhook.{{ .Release.Namespace }}.svc
  dnsNames:
  - {{ include "ess-system.fullname" $ }}-{{ (index .Values "element-operator").namePrefix }}-conversion-webhook.{{ .Release.Namespace }}.svc
  secretName: {{ include "ess-system.fullname" $ }}-{{ (index .Values "element-operator").namePrefix }}-selfsigned-certs
  # 1 year
  duration: 8766h0m0s
  # 6 months
  renewBefore: 4380h0m0s
  privateKey:
    algorithm: RSA
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
  issuerRef:
    name: {{ include "ess-system.fullname" $ }}-webhook
    kind: Issuer
    group: cert-manager.io
{{ end }}
