# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: synapses.matrix.element.io
spec:
  group: matrix.element.io
  names:
    kind: Synapse
    listKind: SynapseList
    plural: synapses
    singular: synapse
    shortNames:
      - syn
  scope: Namespaced
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundleReplacedByHelmBuild:
        service:
          namespace: system
          name: element-conversion-webhook
          path: /convert
      conversionReviewVersions:
        - v1
        - v1beta1
  versions:
    - name: v1alpha2
      schema:
        openAPIV3Schema:
          description: Synapse is the Schema for the synapses API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of Synapse
              type: object
              properties:
                ingress:
                  description: This field will be generated by kustomize
                image:
                  description: Defines the image to be used for Synapse & associated helpers
                  type: object
                  properties:
                    pullSecrets:
                      description: Pull secrets to make available for any of the images below
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            description: The name of the image pull secret in this namespace to use
                            type: string
                    repository:
                      description: Image repository to use for Synapse
                      type: string
                    tag:
                      description: Image tag in the repository to use for Synapse
                      type: string
                    digest:
                      description: Image digest. If defined, this will be used instead of image tag. Image tag is still mandatory to render annotations on the statefulsets and deployments.
                      type: string
                    haproxyRepository:
                      description: Image repository to use for Synapse's Haproxy
                      type: string
                    haproxyTag:
                      description: Image tag in the repository to use for Synapse's Haproxy
                      type: string
                    haproxyDigest:
                      description: Image digest in the repository to use for Synapse's Haproxy
                      type: string
                    redisRepository:
                      description: Image repository to use for Synapse's Redis
                      type: string
                    redisTag:
                      description: Image tag in the repository to use for Synapse's Redis
                      type: string
                    redisDigest:
                      description: Image digest in the repository to use for Synapse's Redis
                      type: string
                    passUserIdToSynapse:
                      description: Deprecated, ignored. Whether to override detection of UID environment flag passed into the synapse docker image
                      type: string
                      enum:
                        - Always
                        - Never
                    pullPolicy:
                      description: Image pull policy for Synapse
                      type: string
                      enum:
                        - Always
                        - IfNotPresent
                        - Never
                    haproxyPullPolicy:
                      description: Image pull policy for HAProxy
                      type: string
                      enum:
                        - Always
                        - IfNotPresent
                        - Never
                    redisPullPolicy:
                      description: Image pull policy for Redis
                      type: string
                      enum:
                        - Always
                        - IfNotPresent
                        - Never
                service:
                  description: This field will be generated by kustomize
                workloads:
                  description: Custom properties on Synapse workloads
                  type: object
                  properties:
                    haproxy:
                      description: This field will be generated by kustomize
                    redis:
                      description: This field will be generated by kustomize
                    synapse:
                      description: This field will be generated by kustomize
                config:
                  description: Defines how to configure Synapse itself
                  type: object
                  properties:
                    externalSecret:
                      description: |
                        The Secret that is managed outside of the Synapse CRD lifecycle.
                        The Secret must contain at least the following keys - macaroon,
                        postgresPassword, registrationSharedSecret, signingKey.

                        It can optionally contain shared.yaml, main.yaml and <worker type>.yaml.
                        If these exist they will be added to all Synapse processes, just the main
                        Synapse process or all processes of a given worker type respectively.
                      type: object
                      properties:
                        name:
                          description: The name of the Secret within the same namespace as the Synapse CRD
                          type: string
                    serverName:
                      description: The server name that User/Room/Group IDs will use in Matrix
                      type: string
                    database:
                      description: This field will be generated by kustomize
                    media:
                      description: Configuration of Synapse's Media store
                      type: object
                      required:
                        - volumeClaim
                      properties:
                        volumeClaim:
                          description: PersistentVolumeClaim that exists within the same namespace as the Synapse CRD
                          type: string
                    applicationServicesRegistrations:
                      description: |
                        Name of the ConfigMaps containing the registration.yml files to connect an AS to Synapse.
                      type: array
                      items:
                        type: string
                    log:
                      description: Synapse Logging settings
                      type: object
                      default: {}
                      properties:
                        rootLevel:
                          type: string
                          description: The maximum level of Synapse log output before any overrides
                          default: Info
                          enum:
                            - Critical
                            - Error
                            - Warning
                            - Info
                            - Debug
                        levelOverrides:
                          description: Logging level overrides for specific Synapse loggers
                          type: object
                          additionalProperties:
                            description: The maximum level of Synapse log output for this specific logger
                            type: string
                            enum:
                              - Critical
                              - Error
                              - Warning
                              - Info
                              - Debug
                    workers:
                      description: The list of the workers to use
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            description: Type of worker being configured.
                            type: string
                            enum:
                              - appservice
                              - background
                              - client-reader
                              - encryption
                              - event-creator
                              - event-persister
                              - federation-inbound
                              - federation-reader
                              - federation-sender
                              - initial-synchrotron
                              - media-repository
                              - presence-writer
                              - pusher
                              - receipts-account
                              - sliding-sync
                              - sso-login
                              - synchrotron
                              - typing-persister
                              - user-dir
                          instances:
                            description: Number of instances of this worker type
                            type: integer
                            default: 1
                          resources:
                            description: This field will be generated by kustomize
                    resources:
                      description: This field will be generated by kustomize
                    containersSecurityContext:
                      description: This field will be generated by kustomize.
                    podSecurityContext:
                      description: This field will be generated by kustomize.
                    redisContainersSecurityContext:
                      description: This field will be generated by kustomize
                    redisPodSecurityContext:
                      description: This field will be generated by kustomize
                    haproxyContainersSecurityContext:
                      description: This field will be generated by kustomize
                    haproxyPodSecurityContext:
                      description: This field will be generated by kustomize
                    redisResources:
                      description: This field will be generated by kustomize
                    haproxyResources:
                      description: This field will be generated by kustomize
                    haproxyReplicas:
                      description: Number of HAProxy replicas to start up. Defaults to 2
                      type: integer
                      default: 2
                      minimum: 1
                    hostAliases:
                      description: This field will be generated by kustomize
            status:
              description: Status defines the observed state of Synapse
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Synapse is the Schema for the synapses API
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            status:
              description: Status defines the observed state of Synapse
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              description: This field will be replaced by kustomize
      served: true
      storage: false
      deprecated: true
      subresources:
        status: {}
