# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: matrixcontentscanners.matrix.element.io
spec:
  group: matrix.element.io
  names:
    kind: MatrixContentScanner
    listKind: MatrixContentScannerList
    plural: matrixcontentscanners
    singular: matrixcontentscanner
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: MatrixContentScanner is the Schema for the matrixcontentscanners API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of MatrixContentScanner
              type: object
              required:
                - config
                - image
              properties:
                config:
                  type: object
                  description: This contains the MatrixContentScanner config
                  required:
                    - matrixServer
                  properties:
                    externalSecret:
                      description: |
                        The Secret that is managed outside of the MatrixContentScanner CRD lifecycle.
                        The Secret must contain at least the following keys - pickleKeyPassword, virusScan.sh.
                      type: object
                      properties:
                        name:
                          description: The name of the Secret within the same namespace as the MatrixContentScanner CRD
                          type: string
                    matrixContentScanner:
                      type: object
                      description: Matrix Content Scanner configuration
                      default: {}
                      properties:
                        replicas:
                          type: number
                          description: The number of replicas on this deployment
                        resources:
                          description: This field will be generated by kustomize
                        containersSecurityContext:
                          description: This field will be generated by kustomize.
                        podSecurityContext:
                          description: This field will be generated by kustomize.
                    clamAntiVirus:
                      type: object
                      description: ClamAntiVirus configuration
                      properties:
                        replicas:
                          type: number
                          description: The number of replicas on this deployment
                        resources:
                          description: This field will be generated by kustomize
                        containersSecurityContext:
                          description: This field will be generated by kustomize.
                        podSecurityContext:
                          description: This field will be generated by kustomize.
                        volumeClaim:
                          type: string
                          description: ClamAntiVirus persistent volume to store virus db
                        freshclam:
                          type: object
                          description: Freshclam settings
                          default: {}
                          properties:
                            dnsDatabaseInfo:
                              type: string
                              default: current.cvd.clamav.net
                              description: Freshclam DNS Database info
                            databaseMirrors:
                              type: array
                              default:
                                - db.local.clamav.net
                                - database.clamav.net
                              items:
                                type: string
                                description: A clamav database mirror
                            proxy:
                              type: object
                              description: The freshclam proxy configuration
                              properties:
                                server:
                                  type: string
                                  description: Proxy server
                                port:
                                  type: number
                                  description: Proxy port
                                username:
                                  type: string
                                  description: Proxy username. `proxyPassword` must be present in the external secret if used.
                    icap:
                      type: object
                      default: {}
                      description: ClamAntiVirus configuration
                      properties:
                        resources:
                          description: This field will be generated by kustomize
                        containersSecurityContext:
                          description: This field will be generated by kustomize.
                        virusScan:
                          type: object
                          description: Virus Scan settings
                          default: {}
                          properties:
                            maxObjectSize:
                              type: string
                              description: The max object size icap will scan
                              default: 5M
                              pattern: "[0-9]+[KMG]"
                            scanFileTypes:
                              type: array
                              description: List of file types scanned by c-icap
                              items:
                                type: string
                                enum:
                                  - EXT
                                  - DATA
                                  - EXECUTABLE
                                  - ARCHIVE
                                  - GRAPHICS
                                  - STREAM
                                  - DOCUMENT
                            sendPercentData:
                              type: number
                              minimum: 0
                              maximum: 100
                              default: 5
                            startSendPercentDataAfter:
                              type: string
                              description: The max object size icap will scan
                              default: 5M
                              pattern: "[0-9]+[KMG]"
                    hostAliases:
                      description: This field will be generated by kustomize
                    matrixServer:
                      description: This field will be generated by kustomize
                    scanning:
                      type: object
                      description: Scanning configuration
                      properties:
                        allowedMimetypes:
                          description: List of allowed MIME types. If a file has a MIME type that's not in this list, its scan is considered failed.
                          type: array
                          items:
                            type: string
                            description: A MIME type.
                    caching:
                      type: object
                      description: Configures caching of scan results.
                      required:
                        - persistentVolumeClaimTemplate
                      properties:
                        maxSize:
                          description: Maximum number of results that can be stored in the cache. If more files are scanned before existing items reach their TTL, the least-recently accessed will be evicted.
                          type: number
                        ttl:
                          description: The maximum amount of time an entry will stay in the cache before being evicted.
                          pattern: "[0-9]+[dwmy]+"
                          type: string
                        maxFileSize:
                          description: The maximum cachable file size. If a file is bigger than this size, a copy of it will be not be cached even if the scan succeeds. If the file is requested again, it is downloaded again from the homeserver, but is not written to disk or scanned.
                          type: string
                          pattern: "[0-9]+[KMGT]B"
                        persistentVolumeClaimTemplate:
                          description: This field will be replaced by kustomize
                download:
                  type: object
                  description: Configures download of medias
                  properties:
                    additionalHeaders:
                      type: object
                      description: Headers to send in outgoing requests.
                      additionalProperties:
                        type: string
                workloads:
                  type: object
                  description: This contains the MatrixContentScanner workloads
                  properties:
                    matrixContentScanner:
                      description: This field will be generated by kustomize
                    clamAntiVirus:
                      description: This field will be generated by kustomize
                image:
                  type: object
                  description: This contains the MatrixContentScanner image
                  properties:
                    matrixContentScanner:
                      description: This field will be generated by kustomize
                    clamAntiVirus:
                      description: This field will be generated by kustomize
                    icap:
                      description: This field will be generated by kustomize
                service:
                  description: This field will be generated by kustomize
            status:
              description: Status defines the observed state of MatrixContentScanner
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
