# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "Wait for the ApplicationServices registration files to be ready"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: "{{ ansible_operator_meta.namespace }}"
    name: "{{ item }}"
  register: regfile_found
  failed_when: regfile_found.resources | length != 1
  loop: "{{ synapse_appservices_registrations }}"

- name: "Lookup the registration files hashes"
  ansible.builtin.set_fact:
    _fetched_registration_files_hash: >
      {{
        (_fetched_registration_files_hash | default([]))
        + [
            (_current_cm | first).data['registration.yaml'] | hash('sha1')
          ]
      }}
  vars:
    _current_cm: >
      {{
        query(
          'kubernetes.core.k8s',
          api_version='v1',
          kind='ConfigMap',
          namespace=ansible_operator_meta.namespace,
          resource_name=item
        )
      }}
  loop: "{{ synapse_appservices_registrations }}"
