# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "Wait for the ApplicationServices registration files to be ready"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: regfile_found
  failed_when: >-
    regfile_found.resources
    | selectattr('metadata.name', 'in', synapse_appservices_registrations)
    | length != (synapse_appservices_registrations | length)

# We make sure that all registration files have a registation.yaml key
# and we build a list of hashes
- name: "Lookup the registration files hashes"
  ansible.builtin.set_fact:
    _fetched_registration_files_hash: >
      {{
        (
          regfile_found.resources
          | selectattr('metadata.name', 'in', synapse_appservices_registrations)
          | map(attribute='data')
          | json_query('[]."registration.yaml"')
          | map('hash', 'sha1')
        )
      }}
  failed_when: (_fetched_registration_files_hash | length) != (synapse_appservices_registrations | length)
