{{- if $.Values.clusterDeployment }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: '{{ .Values.clusterDeployment | ternary "ClusterRole" "Role" }}'
metadata:
  name: '{{ include "elementOperator.prefix" . }}-metrics-reader'
  {{- if not $.Values.clusterDeployment }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{ end }}
