{{- if $.Values.deployCrdRoles }}
{{- if $.Values.deployCrds }}
apiVersion: rbac.authorization.k8s.io/v1
kind: '{{ .Values.clusterDeployment | ternary "ClusterRole" "Role" }}'
metadata:
  name: elementweb-viewer
  {{- if not $.Values.clusterDeployment }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
rules:
  - apiGroups:
      - matrix.element.io
    resources:
      - elementwebs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - matrix.element.io
    resources:
      - elementwebs/status
    verbs:
      - get
{{ end }}
{{ end }}
