{{- if $.Values.deployManager }}
{{- if $.Values.clusterDeployment }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: '{{ include "elementOperator.controllerManagerFullname" . }}'
  name: '{{ include "elementOperator.prefix" . }}-controller-manager-metrics'
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/instance: '{{ include "elementOperator.controllerManagerFullname" . }}'
{{ end }}
{{ end }}
