{{- if $.Values.deployManager }}
apiVersion: v1
kind: Service
metadata:
{{- if $.Values.operator.annotations }}
  annotations:
    {{- toYaml $.Values.operator.annotations | nindent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/instance: '{{ include "elementOperator.controllerManagerFullname" . }}'
{{- if $.Values.operator.labels }}
    {{- toYaml $.Values.operator.labels | nindent 4 }}
{{- end }}
  name: '{{ include "elementOperator.controllerManagerFullname" . }}-metrics'
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: metrics
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: '{{ include "elementOperator.controllerManagerFullname" . }}'
{{ end }}
