# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
kinds_to_teardown: "{{ default_kinds_to_teardown + additional_kinds_to_teardown }}"
default_kinds_to_teardown:
- kind: Deployment
  api_version: apps/v1
- kind: StatefulSet
  api_version: apps/v1
- kind: DaemonSet
  api_version: apps/v1
- kind: Secret
  api_version: v1
- kind: ConfigMap
  api_version: v1
- kind: Service
  api_version: v1
- kind: Ingress
  api_version: networking.k8s.io/v1

additional_kinds_to_teardown: []
