# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: Maintain statefulsets resources
  block:
  - name: Apply statefulsets
    kubernetes.core.k8s:
      resource_definition: "{{ _statefulsets_resources }}"
    register: _sts
  rescue:
  - name: Destroy statefulsets when they cant be redeployed
    when: "'updates to statefulset spec for fields other than' in _sts.msg"
    block:
    - name: Destroy statefulset
      kubernetes.core.k8s:
        state: absent
        resource_definition: "{{ _statefulsets_resources }}"

    - name: Apply statefulsets from scratch
      kubernetes.core.k8s:
        resource_definition: "{{ _statefulsets_resources }}"

  - name: Throw error if it is not statefulset spec update related
    when: "'updates to statefulset spec for fields other than' not in _sts.msg"
    ansible.builtin.fail:
      msg: "{{ _sts.msg }}"
