# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


FROM golang:1.21-alpine AS buildstage
ARG TARGETPLATFORM
ARG BUILDPLATFORM

WORKDIR /app
COPY . /app
RUN go mod download
RUN go build -o /app/conversion-webhook cmd/operator/main.go

FROM alpine:latest
WORKDIR /
COPY --from=buildstage /app/conversion-webhook /usr/bin/conversion-webhook
EXPOSE 8443
USER 1000:1000
ENTRYPOINT ["/usr/bin/conversion-webhook"]
