# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


namePrefix:
clusterDeployment: true
deployCrds: true
deployCrdRoles: true
deployManager: true
deployServiceMonitor: true
crds:
  annotations: {}
  conversionWebhook:
    extraPodSpec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65100
        fsGroup: 65100
    extraContainerSpec:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
    tlsSecretName: ""
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 50Mi
    imagePullPolicy: Always
    image:
      repository: docker.io/vectorim/ess-core-operator-conversion-webhook
      tag: 2.19.0
operator:
  extraPodSpec:
    securityContext:
      runAsNonRoot: true
      runAsUser: 65200
      fsGroup: 65200
  manager:
    # maxConcurrentReconciles should be a factor of the memory limit
    # as a rule of thumb, each reconciles need ~256Mi at peak
    # the value is computed automatically if a memoryLimit is set
    # and this value is not set
    # maxConcurrentReconciles:
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 10m
        memory: 256Mi
    extraEnvs:
      - name: DEBUG_MANIFESTS
        value: "0"
      - name: ANSIBLE_VERBOSITY
        value: "0"
    extraContainerSpec:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
    imagePullPolicy: Always
    image:
      repository: docker.io/vectorim/ess-core-operator
      tag: 2.19.0
  rbacProxy:
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 10m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    extraContainerSpec:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
    imagePullPolicy: Always
    image:
      repository: quay.io/brancz/kube-rbac-proxy
      tag: v0.18.0
