# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: Fetch components secrets
  vars:
    _secret_names: >-
      {{
        components
            | dict2items(key_name='component', value_name='properties')
            | map(attribute='properties')
            | flatten
            | map(attribute='secret_name')
      }}
  block:
  - name: "Fetch all components secrets"
    no_log: "{{ lookup('env', 'DEBUG_MANIFESTS') | int != 1 }}"
    ansible.builtin.set_fact:
      _all_secrets_yaml: |
        {% for item in _secret_names %}
        {{ query('kubernetes.core.k8s',
                    kind='Secret',
                    api_version='v1',
                    resource_name=item,
                    namespace=ansible_operator_meta.namespace)
          | to_nice_yaml
        }}
        ---
        {% endfor %}

  - name: Build all secrets variable
    no_log: "{{ lookup('env', 'DEBUG_MANIFESTS') | int != 1 }}"
    ansible.builtin.set_fact:
      _all_secrets: >-
        {{
          _all_secrets_yaml | split('---') | select | map('from_yaml') | flatten | select
        }}

  - name: Assert length of secrets
    vars:
      _components_ids_with_optional_secret_name: >-
        {{
          components_properties | selectattr('secret_name_is_optional', 'eq', true) | map(attribute='id')
        }}
      _mandatory_secret_names: >-
        {{
          ((components
            | dict2items
            | rejectattr('key', 'in', _components_ids_with_optional_secret_name)
            | rejectattr('key', 'eq', 'irc_bridges')
            | items2dict).values()
            | map(attribute='secret_name')
          ) + (components.irc_bridges
                | default([])
                | map(attribute='secret_name')
              )
        }}
    ansible.builtin.assert:
      that: >-
        (_all_secrets | selectattr('metadata.name', 'in', _mandatory_secret_names) | length) == (_mandatory_secret_names | length)
      msg: |
          Some component secret are missing
          Expected : {{ _mandatory_secret_names | join(', ') }}
          Found : {{ _all_secrets | map(attribute='metadata.name') | join(', ') }}
