# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: Fetch components secrets
  ansible.builtin.set_fact:
    _all_secrets: >
      {{
        (
          query('kubernetes.core.k8s',
                kind='Secret',
                api_version='v1',
                namespace=ansible_operator_meta.namespace)
          | selectattr('metadata.name', 'in', _all_secret_names)
        )
      }}
  vars:
    _all_secret_names: >
      {{
        components
        | dict2items(key_name='component', value_name='properties')
        | map(attribute='properties')
        | flatten
        | map(attribute='secret_name')
      }}
