# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: Fetch global secret
  ansible.builtin.set_fact:
    _global_secret: >
      {{
          query('kubernetes.core.k8s',
                kind='Secret',
                api_version='v1',
                resource_name=_global.secret_name,
                namespace=ansible_operator_meta.namespace)
      }}

- name: Check that the global secret was found
  ansible.builtin.assert:
    that: _global_secret | length == 1
    msg: The global secret {{ _global.secret_name }} could not be found

- name: Check that the generic shared secret is present
  ansible.builtin.assert:
    that: _global.config.generic_shared_secret_secret_key in _global_secret[0].data
    msg: Missing generic shared secret from global secret
