# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: Fetch global secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ ansible_operator_meta.namespace }}"
    name: "{{ global.secret_name }}"
  register: _global_secret

- name: Check that the generic shared secret is present
  ansible.builtin.fail:
    msg: Missing generic shared secret from global secret
  when: (global.config.generic_shared_secret_secret_key not in _global_secret.resources[0].data)
