# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: Merge initial-synchrotron paths into synchrotron paths if initial variant is absent
  ansible.builtin.set_fact:
    synapse_available_worker_types: >
      {{ synapse_available_worker_types
      | combine(
          {
            'synchrotron':
              {
                'paths': synapse_available_worker_types['synchrotron'].paths
                         + synapse_available_worker_types['initial-synchrotron'].paths
              }
          },
          recursive=True
        )
      }}
  when: not synapse_has['initial-synchrotron']

- name: "Manage manifests"
  ansible.builtin.include_role:
    name: "generic_apply"
  vars:
    _manifest_files: >
      {{
        query('fileglob', 'templates/manifests/haproxy_*.yaml.j2') + [
          role_path ~ '/../synapse/templates/manifests/synapse_http_service.yaml.j2',
          role_path ~ '/../synapse/templates/manifests/synapse_ingress.yaml.j2',
        ]
      }}
