# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: Validation
  ansible.builtin.import_tasks: validation.yml

- name: Dependencies
  ansible.builtin.import_tasks: dependencies.yml

- name: Shared
  ansible.builtin.import_tasks: shared.yml

- name: Setup redis
  ansible.builtin.import_tasks: redis_setup.yml
  when: 'has_any_workers'

- name: Synapse process
  ansible.builtin.import_tasks: synapse_process.yml
  vars:
    process_type: main
    process_app: synapse.app.homeserver
    process_additional: "{{ config.additional_main | default('') }}"
    process_resources: "{{ config.resources | default(synapse_resources) }}"
    has_replication: true
    has_http: true
    has_media: "{{ not synapse_has['media-repository'] }}"
    num_instances: 1
    can_only_have_one: true

- name: Worker processes
  ansible.builtin.include_tasks: synapse_process.yml
  loop: "{{ synapse_configured_workers | dict2items }}"
  loop_control:
    loop_var: worker
  vars:
    process_type: "{{ synapse_available_worker_types[worker.key].name_override | default(worker.key) }}"
    process_app: "synapse.app.{{ synapse_available_worker_types[worker.key].app }}"
    process_additional: "{{ worker.value.additional | default('') }}"
    process_resources: "{{ worker.value.resources | default(config.resources) }}"
    has_replication: "{{ synapse_available_worker_types[worker.key].stream_writers | default([]) | length > 0 }}"
    has_http: "{{ synapse_available_worker_types[worker.key].paths | default([]) | length > 0 }}"
    has_media: "{{ worker.key == 'media-repository' }}"
    num_instances: "{{ worker.value.instances }}"
    can_only_have_one: "{{ synapse_available_worker_types[worker.key].single }}"

- name: Ingress
  ansible.builtin.import_tasks: ingress.yml

- name: "Manage manifests"
  ansible.builtin.include_role:
    name: "generic_apply"
  vars:
    _rendered_manifests_strings: "{{ synapse_manifests }}"
