# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "Construct Redis manifests"
  ansible.builtin.set_fact:
    synapse_manifests: "{{ synapse_manifests + query('template', item) }}"
  loop: "{{ _manifest_template_filenames }}"
  vars:
    _manifest_template_filenames: "{{ query('fileglob', 'templates/manifests/redis_*.yaml.j2') }}"
