# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: Import all shared
  ansible.builtin.include_tasks: '{{ item }}'
  loop: "{{ query('fileglob', 'shared/*.yml') | sort }}"
