# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
# It is somewhat tempting to put the specific ConfigMap into the shared ConfigMap however
# a) that isn't needed
# b) imposes the complexity of having to loop on worker types in multiple places
#    e.g. defining has_replication, has_http, process_additional, etc
- name: "Construct manifests - {{ process_type }}"
  ansible.builtin.set_fact:
    synapse_manifests: "{{ synapse_manifests + query('template', item) }}"
  loop: "{{ _manifest_template_filenames }}"
  vars:
    _manifest_template_filenames:
    - "{{ role_path }}/../synapse/templates/manifests/synapse_service.yaml.j2"
    - "{{ role_path }}/../synapse/templates/manifests/synapse_config_secrets.yaml.j2"
    - "{{ role_path }}/../synapse/templates/manifests/synapse_statefulset.yaml.j2"
