# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


- op: add
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/global/properties/k8s/properties/monitoring/properties/serviceMonitor/properties/deploy/default'
  value: auto
- op: add
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/global/properties/k8s/properties/workloads/properties/securityContext/properties/forceUidGid/default'
  value: enable
- op: add
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/global/properties/k8s/properties/workloads/properties/securityContext/properties/setSecComp/default'
  value: enable
- op: add
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/global/properties/k8s/properties/workloads/properties/hostAliases/default'
  value: []
- op: add
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/global/properties/k8s/properties/ingresses/properties/services/properties/type/default'
  value: ClusterIP
- op: add
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/global/properties/k8s/properties/workloads/properties/replicas'
  value:
    type: number
    description: The number of replicas for workloads supporting it
    minimum: 1
    default: 2
