# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


# ElementWeb
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/elementWeb/properties/k8s/properties/workloads/properties/securityContext/properties/runAsUser/default
  value: 10004
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/elementWeb/properties/k8s/properties/workloads/properties/securityContext/properties/fsGroup/default
  value: 10004
# matrixContentScanner
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/matrixContentScanner/properties/k8s/properties/clamAntiVirus/properties/workloads/properties/securityContext/properties/runAsUser/default
  value: 10150
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/matrixContentScanner/properties/k8s/properties/clamAntiVirus/properties/workloads/properties/securityContext/properties/fsGroup/default
  value: 10150
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/matrixContentScanner/properties/k8s/properties/icap/properties/workloads/properties/securityContext/properties/runAsUser/default
  value: 10152
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/matrixContentScanner/properties/k8s/properties/icap/properties/workloads/properties/securityContext/properties/fsGroup/default
  value: 10152
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/matrixContentScanner/properties/k8s/properties/matrixContentScanner/properties/workloads/properties/securityContext/properties/runAsUser/default
  value: 10151
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/matrixContentScanner/properties/k8s/properties/matrixContentScanner/properties/workloads/properties/securityContext/properties/fsGroup/default
  value: 10151
# slidingSync
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/slidingSync/properties/k8s/properties/api/properties/workloads/properties/securityContext/properties/runAsUser/default
  value: 10130
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/slidingSync/properties/k8s/properties/api/properties/workloads/properties/securityContext/properties/fsGroup/default
  value: 10130
# Synapse
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/synapse/properties/k8s/properties/synapse/properties/workloads/properties/securityContext/properties/runAsUser/default
  value: 10991
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/synapse/properties/k8s/properties/synapse/properties/workloads/properties/securityContext/properties/fsGroup/default
  value: 10991
# Synapse-HAProxy
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/synapse/properties/k8s/properties/haproxy/properties/workloads/properties/securityContext/properties/runAsUser/default
  value: 10001
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/synapse/properties/k8s/properties/haproxy/properties/workloads/properties/securityContext/properties/fsGroup/default
  value: 10001
# Synapse-Redis
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/synapse/properties/k8s/properties/redis/properties/workloads/properties/securityContext/properties/runAsUser/default
  value: 10002
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/synapse/properties/k8s/properties/redis/properties/workloads/properties/securityContext/properties/fsGroup/default
  value: 10002
# WellKnownDelegation
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/wellKnownDelegation/properties/k8s/properties/workloads/properties/securityContext/properties/runAsUser/default
  value: 10003
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/wellKnownDelegation/properties/k8s/properties/workloads/properties/securityContext/properties/fsGroup/default
  value: 10003
