# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


# Remove WellKnownDelegation ingress fqdn, its using global domain_name.
# As there's no FQDN there's no need for an ingress object so we might not have annotations set
- op: remove
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/wellKnownDelegation/properties/k8s/properties/ingress/properties/fqdn'
- op: remove
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/wellKnownDelegation/properties/k8s/properties/ingress/required'
- op: add
  path: '/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/components/properties/wellKnownDelegation/properties/k8s/properties/ingress/default'
  value: {}
