# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "ElementDeployment"
  ansible.builtin.import_playbook: "any.yml"
  vars:
    # - it needs to cleanup the same kinds as the operator CRDs (default_kinds_to_teardown in the role)
    # - it needs to cleanup ServiceMonitors
    # - it needs to cleanup operator managed CRDs
    # - PVCs could be here but are deliberately excluded out of an abundance of caution
    additional_kinds_to_teardown: "{{ element_operator_crds + [{'kind': 'ServiceMonitor', 'api_version': 'monitoring.coreos.com/v1'}] }}"
