# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "MatrixContentScanner"
  ansible.builtin.import_playbook: "any.yml"
  vars:
    _kind: "MatrixContentScanner"
