# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "Synapse"
  ansible.builtin.import_playbook: "any.yml"
  vars:
    _kind: "Synapse"
    _crd_hash_version: "2023-10-10"
