# Copyright 2023 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "Display input"
  ansible.builtin.debug:
    msg: "{{ item.input }}"
  when: lookup('env', 'DEBUG_MANIFESTS') | int == 1
  loop_control:
    label: "{{ item.name }}"
  loop:
  - name: "global"
    input: "{{ _global }}"
  - name: "components"
    input: "{{ components }}"
  - name: "secret"
    input: "{{ _global_secret }}"

- name: Use generic apply
  ansible.builtin.include_role:
    name: "generic_apply"
  vars:
    _manifest_files: "{{ query('fileglob', 'templates/' + _component_item + '/*.j2') | sort | list }}"
  loop: "{{ components.keys() | sort_apply_order | list }}"
  loop_control:
    loop_var: _component_item
