# Copyright 2023-2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "Check prerequisites"
  ansible.builtin.include_tasks: "{{ prerequisite_task }}"
  loop: "{{ query('fileglob', 'tasks/prerequisites/*.yml') }}"
  loop_control:
    loop_var: prerequisite_task

- name: "Prepare all components manifests"
  ansible.builtin.include_tasks: prepare.yml


- name: Use generic apply
  ansible.builtin.include_role:
    name: "generic_apply"
  vars:
    _rendered_manifests_strings: "{{ [_all_components_manifests_content] }}"
  when: "_all_components_manifests_content | length > 0"

- name: "Finalising tasks"
  ansible.builtin.include_tasks: "{{ finalising_task }}"
  loop: "{{ query('fileglob', 'tasks/finalising/*.yml') }}"
  loop_control:
    loop_var: finalising_task
