# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "Display input"
  ansible.builtin.debug:
    msg: "{{ item.input }}"
  when: lookup('env', 'DEBUG_MANIFESTS') | int == 1
  loop_control:
    label: "{{ item.name }}"
  loop:
  - name: "global"
    input: "{{ _global }}"
  - name: "components"
    input: "{{ components }}"
  - name: "secret"
    input: "{{ _global_secret }}"

- name: "Build all components manifests"
  ansible.builtin.set_fact:
    _all_components_manifests_content: >-
      {{
        _all_components_manifests_content | default([]) + (
          query('template', *_manifest_template_filenames)
        )
      }}
  vars:
    _manifest_template_filenames: "{{ query('fileglob', 'templates/' + _component_item + '/*.j2') | sort | list }}"
  when: "_manifest_template_filenames | length > 0"
  loop: "{{ components.keys() | sort_apply_order | list }}"
  loop_control:
    loop_var: _component_item
    label: _component_item
