# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-or-later


---
- name: "Display input"
  ansible.builtin.debug:
    msg: "{{ item.input }}"
  when: lookup('env', 'DEBUG_MANIFESTS') | int == 1
  loop_control:
    label: "{{ item.name }}"
  loop:
  - name: "global"
    input: "{{ _global }}"
  - name: "components"
    input: "{{ components }}"
  - name: "secret"
    input: "{{ _global_secret }}"

- name: "Build all components manifests"
  vars:
    # We cannot use `{% set _component_item = ... %}` because the variable used in the set is not reachable outside of jinja engine
    # and ansible cannot use the macros defined in defaults.
    # Instead we use a magic variable injected by ansible into the jinja engine
    # https://github.com/ansible/ansible/blob/devel/lib/ansible/template/__init__.py#L105
    _component_item: "{{ template_path | dirname | basename }}"
  ansible.builtin.set_fact:
    _all_components_manifests_content: |
      {% for _comp in components %}
      {% set _manifest_template_filenames = query('fileglob', 'templates/' + _comp + '/*.j2') | sort | list %}
      {% if _manifest_template_filenames | length > 0 %}
      {% for _template in query('template', *_manifest_template_filenames) %}
      {% if _template | select | length > 0 %}
      {{ _template }}
      ---
      {% endif %}
      {% endfor %}
      {% endif %}
      {% endfor %}
  no_log: "{{ lookup('env', 'DEBUG_MANIFESTS') | int != 1 }}"
