# © 2023 New-Vector
#
# SPDX-License-Identifier: AGPL-3.0-or-later
name: Release Charts

on:
  push:

env:
  VERSION: ${{ github.ref_name }}

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: cpu-s
    container: ghcr.io/element-hq/chart-releaser:cr-push-fix
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global --add safe.directory  "$GITHUB_WORKSPACE"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Move ess-system out of charts dir
        run: |
          mv ./helm/ess-system ess-system-backup

      - name: Run chart-releaser
        uses: element-hq/chart-releaser-action@1389a6afc9af1b11ab9e79267f371d694e4995b2
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: ./helm
          skip_existing: true
          skip_cr_install: true

      - name: Move ess-system back to charts dir
        run: |
          mv ess-system-backup ./helm/ess-system
          rm -rf ./helm/operator
          rm -rf ./helm/updater

      - name: Wait for gh-pages to be up to date
        run: |
          URL="https://element-hq.github.io/ess-starter-edition-core/element-operator-${VERSION}.tar.gz"
          STATUS=0

          while [ $STATUS -ne 200 ]; do
              echo "Checking URL: $URL"
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL)
              if [ $STATUS -ne 200 ]; then
                  echo "Status: $STATUS. Not 200 OK, retrying in 5 seconds..."
                  sleep 5
              else
                  echo "Status: $STATUS. URL is accessible."
              fi
          done

      - name: Run chart-releaser
        uses: element-hq/chart-releaser-action@1389a6afc9af1b11ab9e79267f371d694e4995b2
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: ./helm
          skip_existing: true
          skip_cr_install: true
